### PR TITLE
Add: EmailAutoCompleteTextView by @tasomaniac

### PR DESCRIPTION
**Pull request by tasomaniac**
Here is a gif describing it. 

demo

### CODE REVIEW

**Comment by vbauer** [comment]
Thank you for contribution! This project is available here: http://android-arsenal.com/details/1/2743

**Comment by tasomaniac** [comment]
I will put the badge to my Readme on Monday. Thank you.

**Comment by vbauer** [comment]
@tasomaniac Thank you in advance.

**Comment by tasomaniac** [comment]
One question. I have the library already uploaded to maven central. Can we
disable the described JitPack integration in the website. I would like my
users to use maven central dependency

**Comment by vbauer** [comment]
At the current moment we haven't got this feature on the Android Arsenal, but maybe it will be useful to add it..

**Comment by vbauer** [comment]
This feature has been added on the site. Now you can configure visible tabs.

**Pull request merged**
