### PR TITLE
Added ContentLoadingProgressDialog library

### PR DESCRIPTION
**Pull request by tasomaniac**
ContentLoadingProgressDialog from https://github.com/tasomaniac/ContentLoadingProgressDialog is added.

### CODE REVIEW

**Comment by vbauer** [comment]
@tasomaniac Could you please add screenshot in the [README.md](https://github.com/tasomaniac/ContentLoadingProgressDialog/blob/master/README.md)?

**Comment by tasomaniac** [comment]
I didn't add it because it is just a ProgressDialog with the same look.
What do you think we should do?

**Comment by vbauer** [comment]
@tasomaniac I think it could add additional visibility and show how it looks like, but we can add it without screenshot if you don't want it.

**Comment by tasomaniac** [comment]
We can add the demo app and we can add couple of screenshots from the demo
app.

**Comment by vbauer** [comment]
I've just added project on the site. Now you have permissions to edit information about the project (just login via Github, open details page and click on "Edit" link). Now, you can upload demo app's APK file on the Appetize.io and add their key in the AA ("Live Demo" tab will be available).

**Comment by tasomaniac** [comment]
Thank you, I will add them ASAP.

**Pull request merged**
